version: '3.8'

services:
    server:
        build:
            context: server
            dockerfile: Dockerfile.dev
        volumes:
            - ./static:/usr/src/static
        image: ch-dev-server
        ports:
            - '80:80'
            - '443:443'
        depends_on:
            - app
        restart: always

    app:
        build:
            context: app
            dockerfile: Dockerfile.dev
        image: ch-dev-app
        volumes:
            - ./app:/usr/src/app
            - ./@types:/usr/src/@types
        restart: always
