version: '3.8'

services:
    server:
        build:
            context: .
            dockerfile: ./server/Dockerfile
        volumes:
            - ./static:/usr/src/static
        image: ch-server
        ports:
            - '80:80'
            - '443:443'
        depends_on:
            - api
        restart: always

    api:
        build:
            context: .
            dockerfile: ./api/Dockerfile
        volumes:
            - ./api:/usr/src/api
            - ./@types:/usr/src/@types
        image: ch-api
        restart: always
