version: '3.8'

services:
    server:
        build:
            context: .
            dockerfile: ./server/Dockerfile
        volumes:
            - ./static:/usr/src/static
            - app-dist:/usr/src/app
        image: ch-server
        ports:
            - '80:80'
            - '443:443'
        depends_on:
            - api
            - app

    api:
        build:
            context: .
            dockerfile: ./api/Dockerfile
        image: ch-api
        restart: always

    app:
        build:
            context: .
            dockerfile: ./app/Dockerfile
        volumes:
            - app-dist:/usr/src/app/dist
        image: ch-app
        restart: always

volumes:
    app-dist:
