version: '3.8'

services:
    server:
        build:
            context: server
            dockerfile: Dockerfile.dev
        volumes:
            - ./static:/usr/src/static
        image: ch-server
        ports:
            - '80:80'

    api:
        build:
            context: api
            dockerfile: Dockerfile.dev
        image: ch-api
        volumes:
            - ./api:/usr/src/api
            - ./@types:/usr/src/@types
        ports:
            - '8080:8080'

    app:
        build:
            context: app
            dockerfile: Dockerfile.dev
        image: ch-app
        volumes:
            - ./app:/usr/src/app
            - ./@types:/usr/src/@types
        ports:
            - '3000:3000'
