root: true
extends:
    - eslint:recommended
    - next
    - plugin:@typescript-eslint/recommended
    - plugin:jsx-a11y/strict
parser: "@typescript-eslint/parser"
plugins:
    - "@typescript-eslint"
    - jsx-a11y
    - sort-imports-es6-autofix
    - prettier
settings:
    next:
        rootDir: [app/, packages/*/]
rules:
    no-console: 2
    no-unused-vars: 0
    "@typescript-eslint/no-unused-vars": 2
    prettier/prettier: 2
    react/function-component-definition:
            - 2
            - namedComponents: "arrow-function"
              unnamedComponents: "arrow-function"
    no-var: 2
    sort-imports-es6-autofix/sort-imports-es6:
        - 2
        - ignoreCase: false
          ignoreMemberSort: false
          memberSyntaxSortOrder:
            - none
            - all
            - multiple
            - single
    "@typescript-eslint/consistent-type-imports":
        - 2
        - prefer: "type-imports"
    object-shorthand:
        - 2
        - always
        - avoidExplicitReturnArrows: true
    no-restricted-imports:
        - 2
        - paths:
            - next/link