name: Corehalla Web - Client
on:
    push:
        branches: [master]

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: Build App
              run: sh ./build_prod.sh
            - name: Deploy to production server
              uses: appleboy/scp-action@master
              with:
                  host: ${{ secrets.CH_PROD_HOST }}
                  username: ${{ secrets.CH_PROD_USERNAME }}
                  port: ${{ secrets.CH_PROD_PORT }}
                  key: ${{ secrets.CH_PROD_PRIVATE_KEY }}
                  source: 'dist'
                  target: 'corehalla'
            - name: Docker Compose
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.CH_PROD_HOST }}
                  username: ${{ secrets.CH_PROD_USERNAME }}
                  port: ${{ secrets.CH_PROD_PORT }}
                  key: ${{ secrets.CH_PROD_PRIVATE_KEY }}
                  script: |
                      cd ~/corehalla
                      docker-compose up -d --build
