name: Corehalla Web - Client
on:
    push:
        branches: [master]

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: Build App
              run: sh ./deploy_prod.sh $HOST $PORT $USERNAME $PRIVATE_KEY
              env:
                  HOST: ${{ secrets.CH_PROD_HOST }}
                  PORT: ${{ secrets.CH_PROD_PORT }}
                  USERNAME: ${{ secrets.CH_PROD_USERNAME }}
                  PRIVATE_KEY: ${{ secrets.CH_PROD_PRIVATE_KEY }}
