name: Corehalla Web - Client
on:
    push:
        branches: [master]

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: Build App
                run: ./deploy_prod ${{ secrets.CH_PROD_HOST }} ${{ secrets.CH_PROD_PORT }} ${{ secrets.CH_PROD_USERNAME }} "${{ secrets.CH_PROD_PRIVATE_KEY }}"