name: Code QA
on: [push]
jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./corehalla
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Lint
            action: yarn ci:lint
          - name: Check Types
            action: yarn ts:check
          - name: Check Deadcode
            action: yarn ci:deadcode
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'
          cache-dependency-path: corehalla/yarn.lock
      - name: ${{ matrix.name }}
        run: |
          yarn ci
          ${{ matrix.action }}