name: Corehalla Wiki
on:
    push:
        branches:
            - master

jobs:
    build:
        name: Corehalla Wiki - Build
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./web/wiki
        steps:
            - name: Checkout Repo
              uses: actions/checkout@master
            - name: Install Dependencies
              run: npm install
            - name: Build
              run: npm run build

            - name: Archive Production Artifact
              uses: actions/upload-artifact@v2
              with:
                  name: dist
                  path: |
                      ./web/wiki/docs/.vuepress/dist
                      ./web/wiki/firebase.json
                      ./web/wiki/.firebaserc

    deploy:
        name: Corehalla Wiki - Deploy
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Download Production Artifact
              uses: actions/download-artifact@v2
              with:
                  name: dist

            - name: Deploy to Firebase
              uses: w9jds/firebase-action@master
              with:
                  args: deploy --only hosting
              env:
                  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
