name: Deploy to Firebase

on:
    push:
        branches:
            - master

jobs:
    deploy_to_firebase_hosting:
        runs-on: ubuntu-latest

        steps:
            - name: Setup node
              uses: actions/setup-node@v2
              with:
                  node-version: 14
            - name: Install deps
              run: npm install
            - name: Build
              run: npm run buil
            - name: Deploy to Firebase
              uses: w9jds/firebase-action@master
              with:
                  args: deploy --only hosting
              env:
                  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
